"""Perfect-restart tests for the FlowGraph node types.

The R2 recipe (test_restart_processes.perfect_restart) applied to the
composed graph classes. Prognostic analysis of the seven node types
(flags live on the shared DataArrayMeta objects in each type's
``fields``, so every composition derives them):

- prms_channel: seg_inflow (advance_type reads the finalized daily
  mean -> inflow_ts_prev) + outflow_ts (the muskingum recursion
  crosses the day boundary) -- pywatershed's own channel restart list.
- starfit family: lake_storage_sub (the hourly marching storage) +
  lake_storage (the daily marching storage; also read by
  starfit_advance_type). lake_storage_old is REGENERATED by every
  advance; the accumulators are zeroed in prepare; the running means
  are recomputed within the day.
- starfit_daily adds lake_outflow_sub_next (computed at day end, read
  at the next day's first substep -- the one-day lag).
- pass_through / obsin / source_sink: NO prognostic state (their
  accumulators are zeroed in prepare; obsin's within-day latch never
  crosses the day boundary); the combined starfit_source_sink adds
  none beyond the family storages.

Coverage: the drb pure-channel graph (456 muskingum nodes) + the 115
STARFIT reference reservoirs in both reservoir modes (hourly
n_substeps=1 and daily n_substeps=24, the one-day-lag structure).
"""

import pathlib as pl
import sys
from typing import Any

import numpy as np
import pytest
import xarray as xr

sys.path.append(str(pl.Path(__file__).parent.parent))
sys.path.append(str(pl.Path(__file__).parent))
from conftest import STARFIT_INDS_TEST, pyws_domain_files
from discretization import Discretization
from flow_graph import make_flow_graph
from hydrology.obsin_flow_node import ObsInFlowNode
from hydrology.pass_through_flow_node import PassThroughFlowNode
from hydrology.prms_channel_flow_node import PRMSChannelFlowNode
from hydrology.source_sink_flow_node import SourceSinkFlowNode
from hydrology.starfit_daily_flow_node import StarfitDailyFlowNode
from hydrology.starfit_flow_node import StarfitFlowNode
from hydrology.starfit_source_sink_flow_node import (
    StarfitSourceSinkFlowNode,
)
from model import Model
from test_restart_processes import perfect_restart

MPIX_ROOT = pl.Path(__file__).parents[4]
STARFIT_DIR = MPIX_ROOT / "pywatershed" / "test_data" / "starfit"
PARAM_FILE = STARFIT_DIR / "starfit_original_parameters.nc"
INFLOW_FILE = STARFIT_DIR / "lake_inflow.nc"

DIS_FLOAT_VARS = ("seg_length", "seg_slope", "seg_depth")
S_PER_TIME = np.float64(60.0 * 60.0 * 24.0)

_drb_missing = [
    str(ff) for ff in pyws_domain_files("drb_2yr") if not ff.exists()
]
drb_skipif = pytest.mark.skipif(
    bool(_drb_missing),
    reason=(
        "pywatershed drb_2yr test data not generated; missing: "
        + ", ".join(_drb_missing[:3])
    ),
)

_starfit_missing = [
    str(ff) for ff in (PARAM_FILE, INFLOW_FILE) if not ff.exists()
]
starfit_skipif = pytest.mark.skipif(
    bool(_starfit_missing),
    reason=(
        "pywatershed starfit test data not found; missing: "
        + ", ".join(_starfit_missing)
    ),
)


def test_flags_derivation_pin():
    """The graph flag set, exactly, over ALL node types (data-free)."""
    graph_class = make_flow_graph(
        (
            PRMSChannelFlowNode,
            PassThroughFlowNode,
            ObsInFlowNode,
            SourceSinkFlowNode,
            StarfitFlowNode,
            StarfitSourceSinkFlowNode,
            StarfitDailyFlowNode,
        ),
        class_name="AllTypesRestartPinGraph",
        n_substeps=24,
    )
    assert set(graph_class.get_restart_variables()) == {
        "seg_inflow",
        "outflow_ts",
        "lake_storage",
        "lake_storage_sub",
        "lake_outflow_sub_next",
    }


@drb_skipif
def test_channel_graph(pyws_domain, tmp_path):
    """drb pure-channel graph (456 muskingum nodes), 60 days."""
    drb = pyws_domain("drb_2yr")
    dis_seg_ds = drb["dis_seg_ds"]
    channel_params_ds = drb["channel_params_ds"]
    n_seg = dis_seg_ds.sizes["nsegment"]

    graph_class = make_flow_graph(
        (PRMSChannelFlowNode,),
        class_name="ChannelRestartGraph",
        n_substeps=24,
    )
    to_graph_index = dis_seg_ds["tosegment"].values.astype(np.int64) - 1
    graph_dis_vars: dict[str, Any] = {
        "to_graph_index": ("nnodes", to_graph_index),
        "node_type": (
            "nnodes",
            np.full(
                n_seg,
                graph_class.node_type_code("prms_channel"),
                dtype=np.int64,
            ),
        ),
        "segment_type": ("nnodes", dis_seg_ds["segment_type"].values),
    }
    for vv in DIS_FLOAT_VARS:
        graph_dis_vars[vv] = ("nnodes", dis_seg_ds[vv].values)
    graph_params = xr.Dataset(
        {
            vv: ("nnodes", channel_params_ds[vv].values)
            for vv in ("mann_n", "x_coef")
        }
    )
    node_inputs = {
        f"node_{nn}": drb["node_vol_input"](nn, f"node_{nn}", 0)
        for nn in ("sroff_vol", "ssres_flow_vol", "gwres_flow_vol")
    }

    def make_model(control):
        process_dict = {
            "flow_graph": {
                "class": graph_class,
                "discretization": "nnodes",
                "parameters": graph_params,
                **node_inputs,
            },
        }
        discretizations = {
            "nnodes": Discretization(
                ["nnodes"],
                parameters=xr.Dataset(graph_dis_vars),
                topo_order={"node_order": "to_graph_index"},
                topo_one_based=False,
            ),
        }
        return Model(
            process_dict, dict(control), discretizations=discretizations
        )

    perfect_restart(make_model, S_PER_TIME, 60, tmp_path)


@starfit_skipif
@pytest.mark.parametrize(
    "node_class, n_substeps",
    [(StarfitFlowNode, 1), (StarfitDailyFlowNode, 24)],
    ids=["starfit", "starfit_daily"],
)
def test_starfit_graph(node_class, n_substeps, tmp_path):
    """The 115 reference reservoirs as isolated outlets (cms graph),
    90 days -- hourly (the marching lake_storage_sub) and daily (the
    one-day-lag lake_outflow_sub_next)."""
    with xr.load_dataset(PARAM_FILE) as ds:
        sub = ds.isel(nreservoirs=STARFIT_INDS_TEST).load()
    # pywatershed node data-prep (as in test_starfit_flow_node.py)
    obs = sub["Obs_MEANFLOW_CUMECS"].values
    wh_nan = np.isnan(obs)
    obs[wh_nan] = sub["inflow_mean"].values[wh_nan]
    param_names = [
        nn
        for nn, mm in StarfitFlowNode.fields.items()
        if mm.kind == "parameter"
    ]
    graph_params = xr.Dataset(
        {nn: ("nnodes", sub[nn].values) for nn in param_names}
    )
    with xr.load_dataset(INFLOW_FILE) as ds:
        inflow_da = ds["lake_inflow"].isel(grand_id=STARFIT_INDS_TEST).load()
    n_nodes = len(STARFIT_INDS_TEST)

    graph_class = make_flow_graph(
        (node_class,),
        class_name=f"{node_class.__name__}RestartGraph",
        n_substeps=n_substeps,
        io_in_cfs=False,
    )
    time_vals = inflow_da["time"].values

    def vol_input(name, vals):
        return xr.DataArray(
            vals,
            dims=("time", "nnodes"),
            coords={"time": time_vals},
            name=name,
        )

    node_inputs = {
        "node_sroff_vol": vol_input(
            "node_sroff_vol", inflow_da.values * float(S_PER_TIME)
        ),
        "node_ssres_flow_vol": vol_input(
            "node_ssres_flow_vol", np.zeros(inflow_da.shape)
        ),
        "node_gwres_flow_vol": vol_input(
            "node_gwres_flow_vol", np.zeros(inflow_da.shape)
        ),
    }

    def make_model(control):
        process_dict = {
            "flow_graph": {
                "class": graph_class,
                "discretization": "nnodes",
                "parameters": graph_params,
                **node_inputs,
            },
        }
        discretizations = {
            "nnodes": Discretization(
                ["nnodes"],
                parameters=xr.Dataset(
                    {
                        "to_graph_index": (
                            "nnodes",
                            np.full(n_nodes, -1, dtype=np.int64),
                        ),
                        "node_type": (
                            "nnodes",
                            np.full(
                                n_nodes,
                                graph_class.node_type_code(
                                    node_class.type_name
                                ),
                                dtype=np.int64,
                            ),
                        ),
                    }
                ),
                topo_order={"node_order": "to_graph_index"},
                topo_one_based=False,
            ),
        }
        return Model(
            process_dict, dict(control), discretizations=discretizations
        )

    perfect_restart(make_model, S_PER_TIME, 90, tmp_path)
