name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist pytest-cov numpy xarray netcdf4 pathlib ruff mypy
          # Install additional dependencies if requirements file exists
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f environment.yml ]; then pip install -r <(grep -E "^\s*-\s+" environment.yml | sed 's/^\s*-\s*//'); fi

      - name: Lint
        run: ruff check xr/

      - name: Format
        run: ruff format --check xr/

      - name: mypy
        run: mypy --check-untyped-defs xr/

      - name: Run tests
        run: |
          cd xr
          python -m pytest tests/ -vv -n=4 --cov=. --cov-report=xml --cov-report=term-missing --junitxml=junit.xml

      # - name: Run tests with coverage (Python 3.12 only)
      #   if: matrix.python-version == '3.12'
      #   run: |
      #     pip install coverage
      #     cd xr
      #     python -m coverage run -m pytest tests/
      #     python -m coverage report -m
      #     python -m coverage xml

      - name: Upload coverage to Codecov (Python 3.12 only)
        if: matrix.python-version == '3.12'
        uses: codecov/codecov-action@v3
        with:
          file: ./xr/coverage.xml
          fail_ci_if_error: false

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: ./xr/junit.xml
